apiVersion: v1
kind: Service
metadata:
  name: {{ include "gulab.fullname" . }}
  labels:
    {{- include "gulab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: gulab
      protocol: TCP
      name: gulab
  selector:
    {{- include "gulab.selectorLabels" . | nindent 4 }}
